version: "3"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pozabanka
      POSTGRES_INITDB_ARGS: "--data-checksums"
  documentation:
    build: ./documentation
    volumes:
      - ./documentation:/documentation
    ports:
      - 127.0.0.1:8000:8000
  django:
    build: ./django
    environment:
      SECRET_KEY: hello123
      EMAIL_HOST: sendria
      EMAIL_PORT: "1025"
      EMAIL_HOST_USER: sendria
      EMAIL_HOST_PASSWORD: sendria
      EMAIL_USE_TLS: "false"
      EMAIL_USE_SSL: "false"
    volumes:
      - ./django:/app
    depends_on:
      - db
      - sendria
    ports:
      - 127.0.0.1:8012:8012
  sendria:
    build: ./sendria
    ports:
      - 127.0.0.1:8025:80

